### PR TITLE
Fix for Samsung U28E590

### PR DESCRIPTION
**Pull request by dr1s**
Thanks for the extension, but I couldn't get it to work without this modification on my Samsung U28E590.

### CODE REVIEW

**Comment by daitj** [comment]
Could you post the output of this command here
```
ddcutil getvcp D6 --bus YOUR_MONITOR_BUS
```

I would like to see what is the `0x00` state  in that monitor, because in two different brands I own, 
`0x00` is `Invalid value `
`0x01` is  `DPM: On DPMS: Off` 
`0x02` is `DPM: Off, DPMS: Standby `

**Comment by dr1s** [comment]
```$ ddcutil capabilities --bus 4
Model: Not specified
MCCS version: 2.1
VCP Features:
   Feature: 02 (New control value)
   Feature: 04 (Restore factory defaults)
   Feature: 05 (Restore factory brightness/contrast defaults)
   Feature: 08 (Restore color defaults)
   Feature: 10 (Brightness)
   Feature: 12 (Contrast)
   Feature: 14 (Select color preset)
      Values:
         05: 6500 K
         08: 9300 K
         0b: User 1
         0c: User 2
   Feature: 16 (Video gain: Red)
   Feature: 18 (Video gain: Green)
   Feature: 1A (Video gain: Blue)
   Feature: 52 (Active control)
   Feature: 60 (Input Source)
      Values:
         11: HDMI-1
         12: HDMI-2
         0f: DisplayPort-1
   Feature: AC (Horizontal frequency)
   Feature: AE (Vertical frequency)
   Feature: B2 (Flat panel sub-pixel layout)
   Feature: B6 (Display technology type)
   Feature: C6 (Application enable key)
   Feature: C8 (Display controller type)
   Feature: C9 (Display firmware level)
   Feature: D6 (Power mode)
      Values:
         01: DPM: On,  DPMS: Off
         04: DPM: Off, DPMS: Off
         05: Write only value to turn off display
   Feature: DC (Display Mode)
      Values:
         00: Standard/Default mode
         02: Mixed
         03: Movie
         05: Games
   Feature: DF (VCP Version)
   Feature: FD (Manufacturer specific feature)```
   
I went through the extension and noticed this command wouldn't return the expected value:
```$ ddcutil getvcp --brief D6 --bus 4
VCP D6 SNC x00```

The plugin in turn wouldn't initialize without the change, but it worked with it.

**Comment by daitj** [comment]
What happens when you try to set it to 0x01 

```
ddcutil setvcp D6 0x01 --bus 4
```

and then output of?

```
ddcutil getvcp --brief D6 --bus 4
```

**Comment by dr1s** [comment]
```
$ ddcutil setvcp D6 0x01 --bus 4
Verification failed for feature d6
$ ddcutil getvcp --brief D6 --bus 4
VCP D6 SNC x00
```
what I'm getting from this is that there might be something wrong with my setup or Samsung screwed something up.
If you don't want to merge this thats totally understandable, I will keep my fork until i have time to investigate the problem.

**Comment by daitj** [comment]
I will leave this as it is for now, let see if someone else also reports similar issue, then I think it is better to include this. 

The reason I have this in place is because of multi-monitor setup when monitor configuration changes from dual display to single.
One of the monitor that is not showing any display is still connected via HDMI/DP and still shows current DDC capabilities information but you cannot set anything. 

Without this fix both displays were shown on the menu while you could only set brightness in one.

**Comment by dr1s** [comment]
You're reasons totally make sense and I don't really want advocate for a change, but if you look like other solutions like [MonitorControl](https://github.com/MonitorControl/MonitorControl) for Mac which does exactly that.
Settings are still changeable even if the monitor is turned off or switched to a different output.

Anyway these are just my 2 cents and I will not pursue this further.
From what I read the last days is that Samsung is known for not sticking to the spec (just look at the ddcutil issues) and for now it works.
Thats all I need.

Thanks for your extension, it's been a massive help!

**Comment by daitj** [comment]
I need to add one thing in settings "lowest brightness value " right now it is hard coded to 1. Actually, it can be set to 0 also in most devices but some went totally black when it was set to 0.

So when I do that I can add this also as a settings that you can choose whether you want to be able to control brightness when monitor is off as well. So then this check would totally be skipped. 

Then I think everything will be fine, but I cannot give an ETA on that yet.

**Comment by daitj** [comment]
Sorry for the dealy, but it has finally arrived. 
I have added an advanced settings in which you can skip display's state. This should fix your problem.

**Comment by dr1s** [comment]
Thanks you for the update.
While testing it on my system I came upon this weird bug that the slider disables itself again upon closing the settings menu.
I tried reinstalling the extension, but it didn't help.

**Comment by daitj** [comment]
@dr1s 

Could you make a new issue and post your shell log `journalctl -b /usr/bin/gnome-shell` after that happens.

**Pull request closed without merging**
