### PR TITLE
Fix incompatibility with minor GNOME 40 versions

### PR DESCRIPTION
**Pull request by oscfdezdz**
Fixes https://github.com/daitj/gnome-display-brightness-ddcutil/issues/23

### CODE REVIEW

**Comment by daitj** [comment]
which minor version do you have, is it 40.1? It might be better to have that in the array instead of replacing 40?

**Comment by oscfdezdz** [comment]
It should work for every GNOME 40.X version, I have 40.2.

**Comment by daitj** [comment]
But extension might fail to work in 40.3 because of some changes, that is why I do not want to have 40.0. I hope you understand. 

I will push a new version so that it will work in 40.1  and 40.2 since that seems to be the latest version where this extension works normally. 

Can you confirm that it works properly in 40.2?

**Comment by oscfdezdz** [comment]
I understand, I disabled extension version validation and it works perfectly. Thanks!

**Pull request closed without merging**
